version: '3.1'

services:

  hub:
    image: selenium/hub:latest
    volumes:
      - ./web/application:/application
      ports:
        - 4444:4444

  chrome:
    image: selenium/node-chrome:latest
      depends_on:
        - hub
        enviroment:
          -HUB_HOST=hub

